base_url = "https://zola-portfolio-starter-kit.pages.dev"
title = "Zola Portfolio Starter"
description = "Zola portfolio starter theme."

compile_sass = false
build_search_index = false

generate_sitemap = true
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true

[extra]
github_url = "https://github.com/roblesch/zola-portfolio-starter-kit"
repo_url = "https://github.com/roblesch/zola-portfolio-starter-kit"
