name = "portfolio-starter-kit"
description = "Zola + Tailwind CSS port of the Vercel Portfolio Starter Kit."

tags = ["blog", "portfolio", "tailwind"]
license = "MIT"
homepage = "https://github.com/roblesch/portfolio-starter-kit"
min_version = "0.19.2"
demo = "https://zola-portfolio-starter-kit.pages.dev"

[author]
name = "Christian Robles"
homepage = "https://github.com/roblesch"

[original]
author = "Vercel, Inc."
homepage = "https://vercel.com/templates/next.js/portfolio-starter-kit"
repo = "https://github.com/vercel/examples/tree/main/solutions/blog"
