name = "portfolio-starter-kit"
description = "Zola + Tailwind CSS port of the Vercel Portfolio Starter Kit."

# An optional tags to allow quick search
tags = ["blog", "portfolio", "tailwind"]
license = "MIT"
homepage = "https://github.com/roblesch/portfolio-starter-kit"
# The minimum version of Zola required
min_version = "0.19.2"
# An optional live demo URL
demo = "https://zola-portfolio-starter-kit.pages.dev"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
github_url = "https://github.com/roblesch/zola-portfolio-starter-kit"
repo_url = "https://github.com/roblesch/zola-portfolio-starter-kit"

[author]
name = "Christian Robles"
homepage = "https://github.com/roblesch"

[original]
author = "Vercel, Inc."
homepage = "https://vercel.com/templates/next.js/portfolio-starter-kit"
repo = "https://github.com/vercel/examples/tree/main/solutions/blog"
